# pod-preferred-affinity.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-preferred-affinity
spec:
  schedulerName: custom-scheduler
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 80 # High preference weight (will translate to ~8.0 score bonus)
        preference:
          matchExpressions:
          - key: zone
            operator: In
            values:
            - a # Prefer node in zone 'a'
      - weight: 20
        preference:
          matchExpressions:
          - key: zone
            operator: In
            values:
            - b
  containers:
    - name: nginx
      image: "nginx:stable-alpine"
      resources:
         requests:
           cpu: "10m"
           memory: "20Mi"
