# deployment-preferred-affinity.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-preferred-affinity
spec:
  replicas: 1 # You want one instance of this pod
  selector:
    matchLabels:
      app: nginx-preferred # This label connects the Deployment to its Pods
  template: # This is where your Pod specification goes
    metadata:
      labels:
        app: nginx-preferred # Pods created by this Deployment will have this label
    spec:
      schedulerName: custom-scheduler # IMPORTANT: Still tell K8s to use your scheduler
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 80
            preference:
              matchExpressions:
              - key: zone
                operator: In
                values:
                - a
          - weight: 20
            preference:
              matchExpressions:
              - key: zone
                operator: In
                values:
                - b
      containers:
        - name: nginx
          image: "nginx:stable-alpine"
          resources:
             requests:
               cpu: "10m"
               memory: "20Mi"
