apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysbench-memory-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sysbench
  template:
    metadata:
      labels:
        app: sysbench
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - sleep
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: sysbench
        image: severalnines/sysbench:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          while true; do
            sysbench memory --memory-block-size=2G --memory-oper=read --memory-access-mode=rnd --threads=10 --time=3600 run;
          done
      restartPolicy: Always
