# In scheduler/custom-scheduler-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-scheduler
  namespace: kube-system # Deploying to kube-system is common for schedulers
  labels:
    app: custom-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-scheduler
  template:
    metadata:
      labels:
        app: custom-scheduler
    spec:
      serviceAccountName: custom-scheduler-sa # Match RBAC ServiceAccount name
      containers:
      - name: custom-scheduler
        # --- IMPORTANT: Update this image reference ---
        image: gcr.io/famous-arc-457314-q8/custom-scheduler:v1 # Use the tag you just pushed
        imagePullPolicy: Always # Ensure it pulls the latest if tag is reused
        env:
          # --- Configurable Scoring Weights ---
          - name: SCORE_WEIGHT_MEM
            value: "0.5" # Default weight for available memory (0.0 to 1.0+)
          - name: SCORE_WEIGHT_CPU
            value: "0.5" # Default weight for available CPU (idle cores) (0.0 to 1.0+)
          - name: SCORE_WEIGHT_AFFINITY
            value: "1.0" # Default weight for affinity score (adjust multiplier)
          # --- Get Pod Name for Event Reporting ---
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
